language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
env:
  - DJANGO_VERSION=1.7.8
  - DJANGO_VERSION=1.8.2
# command to run tests
install:
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install